name: Auto Sync WordPress Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest WordPress version
        id: get-wordpress-version
        run: |
          python -m pip install -r requirements.txt
          python latest-version.py >> $GITHUB_OUTPUT
          git push

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: steps.get-wordpress-version.outputs.is_update != 'False'
        with:
          tag_name: ${{ steps.get-wordpress-version.outputs.version }}
          name: ${{ steps.get-wordpress-version.outputs.version }}
          body: "WordPress version ${{ steps.get-wordpress-version.outputs.version }}"
          draft: false
          make_latest: "true"
